name = "GeneralizedTransferMatrixMethod"
uuid = "a1920c5b-c27b-4422-a8d5-0f4c3b46df62"
authors = ["Michael T. Enders <michael@michael-enders.com>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
RefractiveIndex = "97a43521-7681-4ec2-835f-5b8ab7e7617e"

[extensions]
UnitfulExt = "Unitful"
RefractiveIndexExt = "RefractiveIndex"

[compat]
RefractiveIndex = "0.4.3"
StaticArrays = "1"
UnPack = "1.0.2"
Unitful = "1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Unitful"]
